using Inveon.Models;
using Microsoft.EntityFrameworkCore;

namespace Inveon.Services.ProductAPI.DbContexts
{
    public class ApplicationDbContext : DbContext
    {
        public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options) : base(options)
        {

        }
        public DbSet<Product> Products { get; set; }
        public DbSet<Category> Categories { get; set; }
        public DbSet<ProductStock> ProductStocks { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);
            
            modelBuilder.Entity<Category>().HasData(
                new Category { CategoryID = 1, CategoryName = "Pantolon" },
                new Category { CategoryID = 2, CategoryName = "Gömlek" },
                new Category { CategoryID = 3, CategoryName = "Tişört" },
                new Category { CategoryID = 4, CategoryName = "Etek" },
                new Category { CategoryID = 5, CategoryName = "Elbise" },
                new Category { CategoryID = 6, CategoryName = "Kapşonlu" },
                new Category { CategoryID = 7, CategoryName = "Ceket" },
                new Category { CategoryID = 8, CategoryName = "Mont" },
                new Category { CategoryID = 9, CategoryName = "Şort" },
                new Category { CategoryID = 10, CategoryName = "Çopap" },
                new Category { CategoryID = 11, CategoryName = "Pijama" }
            );
            modelBuilder.Entity<Brand>().HasData(
                new Brand { BrandId = 1, Name = "Zara" },
                new Brand { BrandId = 2, Name = "Mavi" },
                new Brand { BrandId = 3, Name = "Colins" },
                new Brand { BrandId = 4, Name = "Bershka" },
                new Brand { BrandId = 5, Name = "Oysho" },
                new Brand { BrandId = 6, Name = "H&M" },
                new Brand { BrandId = 7, Name = "DeFacto" },
                new Brand { BrandId = 8, Name = "Decathlon" },
                new Brand { BrandId = 9, Name = "Koton" },
                new Brand { BrandId = 10, Name = "İpekyol" },
                new Brand { BrandId = 11, Name = "Network" },
                new Brand { BrandId = 12, Name = "Beymen" },
                new Brand { BrandId = 13, Name = "Vakko" },
                new Brand { BrandId = 14, Name = "Sarar" },
                new Brand { BrandId = 15, Name = "Nike" },
                new Brand { BrandId = 16, Name = "Puma" }
            );
            
            modelBuilder.Entity<Product>().HasData(
                new Product { ProductId = 1, Color = "Mavi", Cut = "Skinny", Name = "Blue Jeans", Price = 39.99, CurrencyType = "TRY", Description = "Klasik mavi kot pantolon", CategoryID = 1, BrandID = 1, Gender = "Unisex", Material = "Denim", Style = "Casual", Season = "All-season", ImageUrls = "jeans.jpg", DateAdded = DateTime.Now.ToString() },
                new Product { ProductId = 2, Color = "Beyaz", Cut = "Slim-fit", Name = "White T-shirt", Price = 24.99, CurrencyType = "TRY", Description = "Düz beyaz pamuklu tişört", CategoryID = 3, BrandID = 2, Gender = "Unisex", Material = "Cotton", Style = "Basic", Season = "Summer", ImageUrls = "tshirt.jpg", DateAdded = DateTime.Now.ToString() },
                new Product { ProductId = 3, Color = "Siyah", Cut = "Mini", Name = "Black Skirt", Price = 29.99, CurrencyType = "TRY", Description = "Diz boyu siyah etek", CategoryID = 4, BrandID = 3, Gender = "Female", Material = "Polyester", Style = "Formal", Season = "All-season", ImageUrls = "skirt.jpg", DateAdded = DateTime.Now.ToString() },
                new Product { ProductId = 4, Color = "Siyah", Cut = "Oversize", Name = "Hooded Sweatshirt", Price = 45.99, CurrencyType = "TRY", Description = "Kapşonlu sweatshirt", CategoryID = 6, BrandID = 1, Gender = "Unisex", Material = "Fleece", Style = "Casual", Season = "Winter", ImageUrls = "hoodie.jpg", DateAdded = DateTime.Now.ToString() },
                new Product { ProductId = 5, Color = "Mavi", Cut = "Regular", Name = "Kareli Gömlek", Price = 49.99, CurrencyType = "TRY", Description = "Mavi ve beyaz kareli pamuklu gömlek", CategoryID = 2, BrandID = 2, Gender = "Erkek", Material = "Pamuk", Style = "Günlük", Season = "İlkbahar", ImageUrls = "gomlek.jpg", DateAdded = DateTime.Now.ToString()},
                new Product { ProductId = 6, Color = "Siyah", Cut = "Midi", Name = "Dantelli Elbise", Price = 99.99, CurrencyType = "TRY", Description = "Siyah dantelli şık elbise", CategoryID = 5, BrandID = 4, Gender = "Kadın", Material = "Dantel", Style = "Abiye", Season = "Sonbahar", ImageUrls = "elbise.jpg", DateAdded = DateTime.Now.ToString()},
                new Product { ProductId = 7, Color = "Gri", Cut = "Slim-fit", Name = "Spor Ceket", Price = 149.99, CurrencyType = "TRY", Description = "Gri yünlü spor ceket", CategoryID = 7, BrandID = 14, Gender = "Erkek", Material = "Yün", Style = "Spor", Season = "Kış", ImageUrls = "ceket.jpg", DateAdded = DateTime.Now.ToString()},
                new Product { ProductId = 8, Color = "Beyaz", Cut = "Uzun", Name = "Eşofman Altı", Price = 59.99, CurrencyType = "TRY", Description = "Beyaz pamuklu eşofman altı", CategoryID = 10, BrandID = 15, Gender = "Unisex", Material = "Pamuk", Style = "Spor", Season = "Yaz", ImageUrls = "esofman.jpg", DateAdded = DateTime.Now.ToString()},
                new Product { ProductId = 9, Color = "Pembe", Cut = "Kısa", Name = "Kapüşonlu Mont", Price = 79.99, CurrencyType = "TRY", Description = "Pembe kapüşonlu su geçirmez mont", CategoryID = 8, BrandID = 8, Gender = "Kadın", Material = "Naylon", Style = "Spor", Season = "Kış", ImageUrls = "mont.jpg", DateAdded = DateTime.Now.ToString()},
                new Product { ProductId = 10, Color = "Turuncu", Cut = "Uzun", Name = "Çiçekli Elbise", Price = 69.99, CurrencyType = "TRY", Description = "Turuncu çiçekli pamuklu elbise", CategoryID = 5, BrandID = 9, Gender = "Kadın", Material = "Pamuk", Style = "Günlük", Season = "Yaz", ImageUrls = "elbise2.jpg", DateAdded = DateTime.Now.ToString()},
                new Product { ProductId = 11, Color = "Yeşil", Cut = "Dar", Name = "Kot Pantolon", Price = 59.99, CurrencyType = "TRY", Description = "Yeşil kot pantolon", CategoryID = 1, BrandID = 3, Gender = "Erkek", Material = "Kot", Style = "Günlük", Season = "İlkbahar", ImageUrls = "pantolon.jpg", DateAdded = DateTime.Now.ToString()},
                new Product { ProductId = 12, Color = "Bordo", Cut = "Normal", Name = "Tişört", Price = 19.99, CurrencyType = "TRY", Description = "Bordo pamuklu tişört", CategoryID = 3, BrandID = 7, Gender = "Unisex", Material = "Pamuk", Style = "Temel", Season = "Yaz", ImageUrls = "tisort.jpg", DateAdded = DateTime.Now.ToString()},
                new Product { ProductId = 13, Color = "Sarı", Cut = "Mini", Name = "Etek", Price = 34.99, CurrencyType = "TRY", Description = "Sarı kalem etek", CategoryID = 4, BrandID = 10, Gender = "Kadın", Material = "Poliester", Style = "Resmi", Season = "Sonbahar", ImageUrls = "etek.jpg", DateAdded = DateTime.Now.ToString()},
                new Product { ProductId = 14, Color = "Mavi", Cut = "Geniş", Name = "Şort", Price = 29.99, CurrencyType = "TRY", Description = "Mavi kot şort", CategoryID = 9, BrandID = 2, Gender = "Erkek", Material = "Kot", Style = "Günlük", Season = "Yaz", ImageUrls = "sort.jpg", DateAdded = DateTime.Now.ToString()},
                new Product { ProductId = 15, Color = "Mor", Cut = "Oversize", Name = "Kapüşonlu", Price = 39.99, CurrencyType = "TRY", Description = "Mor kapüşonlu pamuklu sweatshirt", CategoryID = 6, BrandID = 6, Gender = "Unisex", Material = "Pamuk", Style = "Günlük", Season = "Kış", ImageUrls = "kapusonlu.jpg", DateAdded = DateTime.Now.ToString()},
                new Product { ProductId = 16, Color = "Kırmızı", Cut = "Slim-fit", Name = "Gömlek", Price = 44.99, CurrencyType = "TRY", Description = "Kırmızı düz pamuklu gömlek", CategoryID = 2, BrandID = 9, Gender = "Erkek", Material = "Pamuk", Style = "Günlük", Season = "İlkbahar", ImageUrls = "gomlek2.jpg", DateAdded = DateTime.Now.ToString()},
                new Product { ProductId = 17, Color = "Bej", Cut = "Uzun", Name = "Trençkot", Price = 149.99, CurrencyType = "TRY", Description = "Bej yünlü trençkot", CategoryID = 8, BrandID = 11, Gender = "Kadın", Material = "Yün", Style = "Şık", Season = "Sonbahar", ImageUrls = "trenckot.jpg", DateAdded = DateTime.Now.ToString()},
                new Product { ProductId = 18, Color = "Siyah", Cut = "Kısa", Name = "Pijama", Price = 49.99, CurrencyType = "TRY", Description = "Siyah saten pijama takımı", CategoryID = 11, BrandID = 5, Gender = "Kadın", Material = "Saten", Style = "Rahat", Season = "Yaz", ImageUrls = "pijama.jpg", DateAdded = DateTime.Now.ToString()},
                new Product { ProductId = 19, Color = "Lacivert", Cut = "Normal", Name = "Polo Yaka Tişört", Price = 34.99, CurrencyType = "TRY", Description = "Lacivert polo yaka tişört", CategoryID = 3, BrandID = 15, Gender = "Erkek", Material = "Pamuk", Style = "Spor", Season = "Yaz", ImageUrls = "polo.jpg", DateAdded = DateTime.Now.ToString()},
                new Product { ProductId = 20, Color = "Gri", Cut = "Midi", Name = "Elbise", Price = 59.99, CurrencyType = "TRY", Description = "Gri triko elbise", CategoryID = 5, BrandID = 6, Gender = "Kadın", Material = "Triko", Style = "Günlük", Season = "Kış", ImageUrls = "elbise3.jpg", DateAdded = DateTime.Now.ToString()},
                new Product { ProductId = 21, Color = "Beyaz", Cut = "Dar", Name = "Pantolon", Price = 54.99, CurrencyType = "TRY", Description = "Beyaz pamuklu pantolon", CategoryID = 1, BrandID = 7, Gender = "Kadın", Material = "Pamuk", Style = "Günlük", Season = "İlkbahar", ImageUrls = "pantolon2.jpg", DateAdded = DateTime.Now.ToString()},
                new Product { ProductId = 22, Color = "Siyah", Cut = "Normal", Name = "Tişört", Price = 19.99, CurrencyType = "TRY", Description = "Siyah baskılı tişört", CategoryID = 3, BrandID = 1, Gender = "Unisex", Material = "Pamuk", Style = "Günlük", Season = "Yaz", ImageUrls = "tisort2.jpg", DateAdded = DateTime.Now.ToString()},
                new Product { ProductId = 23, Color = "Mavi", Cut = "Mini", Name = "Etek", Price = 29.99, CurrencyType = "TRY", Description = "Mavi kot etek", CategoryID = 4, BrandID = 4, Gender = "Kadın", Material = "Kot", Style = "Günlük", Season = "Yaz", ImageUrls = "etek2.jpg", DateAdded = DateTime.Now.ToString()},
                new Product { ProductId = 24, Color = "Yeşil", Cut = "Geniş", Name = "Şort", Price = 24.99, CurrencyType = "TRY", Description = "Yeşil pamuklu şort", CategoryID = 9, BrandID = 8, Gender = "Unisex", Material = "Pamuk", Style = "Spor", Season = "Yaz", ImageUrls = "sort2.jpg", DateAdded = DateTime.Now.ToString()},
                new Product { ProductId = 25, Color = "Pembe", Cut = "Oversize", Name = "Kapüşonlu", Price = 39.99, CurrencyType = "TRY", Description = "Pembe kapüşonlu polar sweatshirt", CategoryID = 6, BrandID = 16, Gender = "Unisex", Material = "Polar", Style = "Spor", Season = "Kış", ImageUrls = "kapusonlu2.jpg", DateAdded = DateTime.Now.ToString()},
                new Product { ProductId = 26, Color = "Turuncu", Cut = "Slim-fit", Name = "Gömlek", Price = 44.99, CurrencyType = "TRY", Description = "Turuncu düz pamuklu gömlek", CategoryID = 2, BrandID = 13, Gender = "Erkek", Material = "Pamuk", Style = "Şık", Season = "İlkbahar", ImageUrls = "gomlek3.jpg", DateAdded = DateTime.Now.ToString() },
                new Product { ProductId = 27, Color = "Kahverengi", Cut = "Uzun", Name = "Kaban", Price = 199.99, CurrencyType = "TRY", Description = "Kahverengi yünlü kaban", CategoryID = 8, BrandID = 12, Gender = "Kadın", Material = "Yün", Style = "Şık", Season = "Kış", ImageUrls = "kaban.jpg", DateAdded = DateTime.Now.ToString() },
                new Product { ProductId = 28, Color = "Lila", Cut = "Kısa", Name = "Pijama", Price = 59.99, CurrencyType = "TRY", Description = "Lila pamuklu pijama takımı", CategoryID = 11, BrandID = 5, Gender = "Kadın", Material = "Pamuk", Style = "Rahat", Season = "Yaz", ImageUrls = "pijama2.jpg", DateAdded = DateTime.Now.ToString() },
                new Product { ProductId = 29, Color = "Siyah", Cut = "Normal", Name = "Polo Yaka Tişört", Price = 34.99, CurrencyType = "TRY", Description = "Siyah polo yaka tişört", CategoryID = 3, BrandID = 16, Gender = "Erkek", Material = "Pamuk", Style = "Spor", Season = "Yaz", ImageUrls = "polo2.jpg", DateAdded = DateTime.Now.ToString() },
                new Product { ProductId = 30, Color = "Bordo", Cut = "Midi", Name = "Elbise", Price = 69.99, CurrencyType = "TRY", Description = "Bordo triko elbise", CategoryID = 5, BrandID = 6, Gender = "Kadın", Material = "Triko", Style = "Günlük", Season = "Kış", ImageUrls = "elbise4.jpg", DateAdded = DateTime.Now.ToString() },
                new Product { ProductId = 31, Color = "Gri", Cut = "Dar", Name = "Pantolon", Price = 64.99, CurrencyType = "TRY", Description = "Gri kot pantolon", CategoryID = 1, BrandID = 3, Gender = "Erkek", Material = "Kot", Style = "Günlük", Season = "İlkbahar", ImageUrls = "pantolon3.jpg", DateAdded = DateTime.Now.ToString() },
                new Product { ProductId = 32, Color = "Beyaz", Cut = "Normal", Name = "Tişört", Price = 19.99, CurrencyType = "TRY", Description = "Beyaz baskılı tişört", CategoryID = 3, BrandID = 1, Gender = "Unisex", Material = "Pamuk", Style = "Günlük", Season = "Yaz", ImageUrls = "tisort3.jpg", DateAdded = DateTime.Now.ToString() },
                new Product { ProductId = 33, Color = "Sarı", Cut = "Mini", Name = "Etek", Price = 39.99, CurrencyType = "TRY", Description = "Sarı çiçekli etek", CategoryID = 4, BrandID = 10, Gender = "Kadın", Material = "Pamuk", Style = "Günlük", Season = "Yaz", ImageUrls = "etek3.jpg", DateAdded = DateTime.Now.ToString() },
                new Product { ProductId = 34, Color = "Yeşil", Cut = "Geniş", Name = "Şort", Price = 24.99, CurrencyType = "TRY", Description = "Yeşil keten şort", CategoryID = 9, BrandID = 8, Gender = "Unisex", Material = "Keten", Style = "Spor", Season = "Yaz", ImageUrls = "sort3.jpg", DateAdded = DateTime.Now.ToString() },
                new Product { ProductId = 35, Color = "Mor", Cut = "Oversize", Name = "Kapüşonlu", Price = 39.99, CurrencyType = "TRY", Description = "Mor kapüşonlu pamuklu sweatshirt", CategoryID = 6, BrandID = 6, Gender = "Unisex", Material = "Pamuk", Style = "Günlük", Season = "Kış", ImageUrls = "kapusonlu3.jpg", DateAdded = DateTime.Now.ToString() },
                new Product { ProductId = 36, Color = "Kırmızı", Cut = "Slim-fit", Name = "Gömlek", Price = 54.99, CurrencyType = "TRY", Description = "Kırmızı çizgili pamuklu gömlek", CategoryID = 2, BrandID = 14, Gender = "Erkek", Material = "Pamuk", Style = "Resmi", Season = "İlkbahar", ImageUrls = "gomlek4.jpg", DateAdded = DateTime.Now.ToString() },
                new Product { ProductId = 37, Color = "Siyah", Cut = "Uzun", Name = "Kaban", Price = 249.99, CurrencyType = "TRY", Description = "Siyah deri kaban", CategoryID = 8, BrandID = 12, Gender = "Erkek", Material = "Deri", Style = "Şık", Season = "Kış", ImageUrls = "kaban2.jpg", DateAdded = DateTime.Now.ToString() },
                new Product { ProductId = 38, Color = "Mavi", Cut = "Kısa", Name = "Pijama", Price = 69.99, CurrencyType = "TRY", Description = "Mavi saten pijama takımı", CategoryID = 11, BrandID = 5, Gender = "Kadın", Material = "Saten", Style = "Rahat", Season = "Yaz", ImageUrls = "pijama3.jpg", DateAdded = DateTime.Now.ToString() },
                new Product { ProductId = 39, Color = "Lacivert", Cut = "Normal", Name = "Polo Yaka Tişört", Price = 34.99, CurrencyType = "TRY", Description = "Lacivert polo yaka tişört", CategoryID = 3, BrandID = 16, Gender = "Erkek", Material = "Pamuk", Style = "Spor", Season = "Yaz", ImageUrls = "polo3.jpg", DateAdded = DateTime.Now.ToString() },
                new Product { ProductId = 40, Color = "Gri", Cut = "Midi", Name = "Elbise", Price = 74.99, CurrencyType = "TRY", Description = "Gri dantelli elbise", CategoryID = 5, BrandID = 6, Gender = "Kadın", Material = "Dantel", Style = "Abiye", Season = "Sonbahar", ImageUrls = "elbise5.jpg", DateAdded = DateTime.Now.ToString() },
                new Product { ProductId = 41, Color = "Bej", Cut = "Dar", Name = "Pantolon", Price = 69.99, CurrencyType = "TRY", Description = "Bej keten pantolon", CategoryID = 1, BrandID = 7, Gender = "Kadın", Material = "Keten", Style = "Günlük", Season = "İlkbahar", ImageUrls = "pantolon4.jpg", DateAdded = DateTime.Now.ToString() },
                new Product { ProductId = 42, Color = "Siyah", Cut = "Normal", Name = "Tişört", Price = 19.99, CurrencyType = "TRY", Description = "Siyah baskılı tişört", CategoryID = 3, BrandID = 1, Gender = "Unisex", Material = "Pamuk", Style = "Günlük", Season = "Yaz", ImageUrls = "tisort4.jpg", DateAdded = DateTime.Now.ToString() },
                new Product { ProductId = 43, Color = "Mavi", Cut = "Mini", Name = "Etek", Price = 49.99, CurrencyType = "TRY", Description = "Mavi payetli etek", CategoryID = 4, BrandID = 4, Gender = "Kadın", Material = "Payet", Style = "Abiye", Season = "Sonbahar", ImageUrls = "etek4.jpg", DateAdded = DateTime.Now.ToString() },
                new Product { ProductId = 44, Color = "Kırmızı", Cut = "Geniş", Name = "Şort", Price = 29.99, CurrencyType = "TRY", Description = "Kırmızı pamuklu şort", CategoryID = 9, BrandID = 2, Gender = "Erkek", Material = "Pamuk", Style = "Günlük", Season = "Yaz", ImageUrls = "sort4.jpg", DateAdded = DateTime.Now.ToString() },
                new Product { ProductId = 45, Color = "Siyah", Cut = "Oversize", Name = "Kapüşonlu", Price = 49.99, CurrencyType = "TRY", Description = "Siyah kapüşonlu deri sweatshirt", CategoryID = 6, BrandID = 6, Gender = "Unisex", Material = "Deri", Style = "Günlük", Season = "Kış", ImageUrls = "kapusonlu4.jpg", DateAdded = DateTime.Now.ToString() },
                new Product { ProductId = 46, Color = "Beyaz", Cut = "Slim-fit", Name = "Gömlek", Price = 64.99, CurrencyType = "TRY", Description = "Beyaz düz pamuklu gömlek", CategoryID = 2, BrandID = 14, Gender = "Erkek", Material = "Pamuk", Style = "Resmi", Season = "İlkbahar", ImageUrls = "gomlek5.jpg", DateAdded = DateTime.Now.ToString() },
                new Product { ProductId = 47, Color = "Yeşil", Cut = "Uzun", Name = "Kaban", Price = 299.99, CurrencyType = "TRY", Description = "Yeşil yünlü kaban", CategoryID = 8, BrandID = 12, Gender = "Erkek", Material = "Yün", Style = "Şık", Season = "Kış", ImageUrls = "kaban3.jpg", DateAdded = DateTime.Now.ToString() },
                new Product { ProductId = 48, Color = "Pembe", Cut = "Kısa", Name = "Pijama", Price = 79.99, CurrencyType = "TRY", Description = "Pembe ipek pijama takımı", CategoryID = 11, BrandID = 5, Gender = "Kadın", Material = "İpek", Style = "Rahat", Season = "Yaz", ImageUrls = "pijama4.jpg", DateAdded = DateTime.Now.ToString() },
                new Product { ProductId = 49, Color = "Turuncu", Cut = "Normal", Name = "Polo Yaka Tişört", Price = 39.99, CurrencyType = "TRY", Description = "Turuncu polo yaka tişört", CategoryID = 3, BrandID = 16, Gender = "Erkek", Material = "Pamuk", Style = "Spor", Season = "Yaz", ImageUrls = "polo4.jpg", DateAdded = DateTime.Now.ToString() },
                new Product { ProductId = 50, Color = "Mor", Cut = "Midi", Name = "Elbise", Price = 89.99, CurrencyType = "TRY", Description = "Mor kadife elbise", CategoryID = 5, BrandID = 6, Gender = "Kadın", Material = "Kadife", Style = "Abiye", Season = "Kış", ImageUrls = "elbise6.jpg", DateAdded = DateTime.Now.ToString() },
                new Product { ProductId = 51, Color = "Sarı", Cut = "Dar", Name = "Pantolon", Price = 74.99, CurrencyType = "TRY", Description = "Sarı kot pantolon", CategoryID = 1, BrandID = 3, Gender = "Kadın", Material = "Kot", Style = "Günlük", Season = "İlkbahar", ImageUrls = "pantolon5.jpg", DateAdded = DateTime.Now.ToString() },
                new Product { ProductId = 52, Color = "Lacivert", Cut = "Normal", Name = "Tişört", Price = 24.99, CurrencyType = "TRY", Description = "Lacivert baskılı tişört", CategoryID = 3, BrandID = 1, Gender = "Unisex", Material = "Pamuk", Style = "Günlük", Season = "Yaz", ImageUrls = "tisort5.jpg", DateAdded = DateTime.Now.ToString() },
                new Product { ProductId = 53, Color = "Siyah", Cut = "Mini", Name = "Etek", Price = 59.99, CurrencyType = "TRY", Description = "Siyah deri etek", CategoryID = 4, BrandID = 4, Gender = "Kadın", Material = "Deri", Style = "Günlük", Season = "Sonbahar", ImageUrls = "etek5.jpg", DateAdded = DateTime.Now.ToString() },
                new Product { ProductId = 54, Color = "Mavi", Cut = "Geniş", Name = "Şort", Price = 34.99, CurrencyType = "TRY", Description = "Mavi pamuklu şort", CategoryID = 9, BrandID = 2, Gender = "Erkek", Material = "Pamuk", Style = "Günlük", Season = "Yaz", ImageUrls = "sort5.jpg", DateAdded = DateTime.Now.ToString() },
                new Product { ProductId = 55, Color = "Kırmızı", Cut = "Oversize", Name = "Kapüşonlu", Price = 59.99, CurrencyType = "TRY", Description = "Kırmızı kapüşonlu yünlü sweatshirt", CategoryID = 6, BrandID = 6, Gender = "Unisex", Material = "Yün", Style = "Günlük", Season = "Kış", ImageUrls = "kapusonlu5.jpg", DateAdded = DateTime.Now.ToString() },
                new Product { ProductId = 56, Color = "Beyaz", Cut = "Slim-fit", Name = "Gömlek", Price = 74.99, CurrencyType = "TRY", Description = "Beyaz düz pamuklu gömlek", CategoryID = 2, BrandID = 14, Gender = "Erkek", Material = "Pamuk", Style = "Resmi", Season = "İlkbahar", ImageUrls = "gomlek6.jpg", DateAdded = DateTime.Now.ToString() },
                new Product { ProductId = 57, Color = "Bej", Cut = "Uzun", Name = "Kaban", Price = 349.99, CurrencyType = "TRY", Description = "Bej kaşmir kaban", CategoryID = 8, BrandID = 12, Gender = "Kadın", Material = "Kaşmir", Style = "Şık", Season = "Kış", ImageUrls = "kaban4.jpg", DateAdded = DateTime.Now.ToString() },
                new Product { ProductId = 58, Color = "Yeşil", Cut = "Kısa", Name = "Pijama", Price = 89.99, CurrencyType = "TRY", Description = "Yeşil ipek pijama takımı", CategoryID = 11, BrandID = 5, Gender = "Kadın", Material = "İpek", Style = "Rahat", Season = "Yaz", ImageUrls = "pijama5.jpg", DateAdded = DateTime.Now.ToString() },
                new Product { ProductId = 59, Color = "Turuncu", Cut = "Normal", Name = "Polo Yaka Tişört", Price = 44.99, CurrencyType = "TRY", Description = "Turuncu polo yaka tişört", CategoryID = 3, BrandID = 16, Gender = "Erkek", Material = "Pamuk", Style = "Spor", Season = "Yaz", ImageUrls = "polo5.jpg", DateAdded = DateTime.Now.ToString() },
                new Product { ProductId = 60, Color = "Mavi", Cut = "Düz", Name = "Kareli Gömlek", Price = 49.99, CurrencyType = "TRY", Description = "Klasik kareli gömlek", CategoryID = 2, BrandID = 4, Gender = "Erkek", Material = "Pamuk", Style = "Günlük", Season = "Sonbahar", ImageUrls = "gomlek.jpg", DateAdded = DateTime.Now.ToString() },
                new Product { ProductId = 61, Color = "Beyaz", Cut = "Midi", Name = "Çiçekli Elbise", Price = 59.99, CurrencyType = "TRY", Description = "Romantik çiçekli elbise", CategoryID = 5, BrandID = 9, Gender = "Kadın", Material = "Viskon", Style = "Şık", Season = "İlkbahar", ImageUrls = "elbise.jpg", DateAdded = DateTime.Now.ToString() },
                new Product { ProductId = 62, Color = "Siyah", Cut = "Regular", Name = "Deri Ceket", Price = 199.99, CurrencyType = "TRY", Description = "Kaliteli deri ceket", CategoryID = 7, BrandID = 13, Gender = "Unisex", Material = "Deri", Style = "Rock", Season = "Kış", ImageUrls = "ceket.jpg", DateAdded = DateTime.Now.ToString() },
                new Product { ProductId = 63, Color = "Gri", Cut = "Şort", Name = "Eşofman Altı", Price = 34.99, CurrencyType = "TRY", Description = "Rahat eşofman altı", CategoryID = 9, BrandID = 15, Gender = "Unisex", Material = "Polar", Style = "Spor", Season = "Yaz", ImageUrls = "esofman.jpg", DateAdded = DateTime.Now.ToString() },
                new Product { ProductId = 64, Color = "Pembe", Cut = "Bol", Name = "Kapüşonlu Mont", Price = 79.99, CurrencyType = "TRY", Description = "Peluş kapüşonlu mont", CategoryID = 8, BrandID = 6, Gender = "Kadın", Material = "Yün", Style = "Sevimli", Season = "Kış", ImageUrls = "mont.jpg", DateAdded = DateTime.Now.ToString() },
                new Product { ProductId = 65, Color = "Turuncu", Cut = "Dar", Name = "Bisikletçi Şortu", Price = 19.99, CurrencyType = "TRY", Description = "Esnek bisikletçi şortu", CategoryID = 9, BrandID = 8, Gender = "Unisex", Material = "Likra", Style = "Spor", Season = "Yaz", ImageUrls = "sort.jpg", DateAdded = DateTime.Now.ToString() },
                new Product { ProductId = 66, Color = "Mor", Cut = "Uzun", Name = "Saten Pijama", Price = 69.99, CurrencyType = "TRY", Description = "Yumuşak saten pijama", CategoryID = 11, BrandID = 5, Gender = "Kadın", Material = "Saten", Style = "Lüks", Season = "Sonbahar", ImageUrls = "pijama.jpg", DateAdded = DateTime.Now.ToString() },
                new Product { ProductId = 67, Color = "Kahverengi", Cut = "Kısa", Name = "Deri Etek", Price = 89.99, CurrencyType = "TRY", Description = "Mini deri etek", CategoryID = 4, BrandID = 4, Gender = "Kadın", Material = "Deri", Style = "Cesur", Season = "İlkbahar", ImageUrls = "etek.jpg", DateAdded = DateTime.Now.ToString() },
                new Product { ProductId = 68, Color = "Yeşil", Cut = "Vücut", Name = "Polo Yaka Tişört", Price = 39.99, CurrencyType = "TRY", Description = "Polo yaka pamuk tişört", CategoryID = 3, BrandID = 14, Gender = "Erkek", Material = "Pamuk", Style = "Şık", Season = "Yaz", ImageUrls = "tisort.jpg", DateAdded = DateTime.Now.ToString() },
                new Product { ProductId = 69, Color = "Lacivert", Cut = "Bootcut", Name = "Kot Pantolon", Price = 59.99, CurrencyType = "TRY", Description = "Rahat kot pantolon", CategoryID = 1, BrandID = 2, Gender = "Erkek", Material = "Denim", Style = "Günlük", Season = "All-season", ImageUrls = "pantolon.jpg", DateAdded = DateTime.Now.ToString() },
                new Product { ProductId = 70, Color = "Sarı", Cut = "Maxi", Name = "Çizgili Elbise", Price = 49.99, CurrencyType = "TRY", Description = "Uzun çizgili elbise", CategoryID = 5, BrandID = 10, Gender = "Kadın", Material = "Keten", Style = "Bohem", Season = "Yaz", ImageUrls = "elbise.jpg", DateAdded = DateTime.Now.ToString() },
                new Product { ProductId = 71, Color = "Kırmızı", Cut = "Slim-fit", Name = "Oxford Gömlek", Price = 69.99, CurrencyType = "TRY", Description = "Kaliteli oxford gömlek", CategoryID = 2, BrandID = 12, Gender = "Erkek", Material = "Oxford", Style = "Formal", Season = "All-season", ImageUrls = "gomlek.jpg", DateAdded = DateTime.Now.ToString() },
                new Product { ProductId = 72, Color = "Bordo", Cut = "Crop", Name = "Kazak", Price = 44.99, CurrencyType = "TRY", Description = "Sıcak kazak", CategoryID = 6, BrandID = 9, Gender = "Kadın", Material = "Akrilik", Style = "Casual", Season = "Kış", ImageUrls = "kazak.jpg", DateAdded = DateTime.Now.ToString() },
                new Product { ProductId = 73, Color = "Bej", Cut = "Trench", Name = "Pardesü", Price = 149.99, CurrencyType = "TRY", Description = "Şık pardesü", CategoryID = 8, BrandID = 11, Gender = "Kadın", Material = "Gabardin", Style = "Elegant", Season = "İlkbahar", ImageUrls = "pardesu.jpg", DateAdded = DateTime.Now.ToString() },
                new Product { ProductId = 74, Color = "Siyah", Cut = "Skinny", Name = "Tayt", Price = 24.99, CurrencyType = "TRY", Description = "Esnek tayt", CategoryID = 10, BrandID = 6, Gender = "Kadın", Material = "Elastan", Style = "Spor", Season = "All-season", ImageUrls = "tayt.jpg", DateAdded = DateTime.Now.ToString() },
                new Product { ProductId = 75, Color = "Mavi", Cut = "Regular", Name = "Polo Tişört", Price = 34.99, CurrencyType = "TRY", Description = "Polo tişört", CategoryID = 3, BrandID = 15, Gender = "Erkek", Material = "Pike", Style = "Spor", Season = "Yaz", ImageUrls = "polo.jpg", DateAdded = DateTime.Now.ToString() },
                new Product { ProductId = 76, Color = "Pembe", Cut = "Mini", Name = "Payetli Elbise", Price = 99.99, CurrencyType = "TRY", Description = "Parlak payetli elbise", CategoryID = 5, BrandID = 4, Gender = "Kadın", Material = "Payet", Style = "Parti", Season = "Yaz", ImageUrls = "payet.jpg", DateAdded = DateTime.Now.ToString() },
                new Product { ProductId = 77, Color = "Turuncu", Cut = "Oversize", Name = "Sweatshirt", Price = 39.99, CurrencyType = "TRY", Description = "Rahat sweatshirt", CategoryID = 6, BrandID = 7, Gender = "Unisex", Material = "Pamuk", Style = "Casual", Season = "Sonbahar", ImageUrls = "sweat.jpg", DateAdded = DateTime.Now.ToString() },
                new Product { ProductId = 78, Color = "Mor", Cut = "Midi", Name = "Dantel Etek", Price = 54.99, CurrencyType = "TRY", Description = "Romantik dantel etek", CategoryID = 4, BrandID = 10, Gender = "Kadın", Material = "Dantel", Style = "Şık", Season = "İlkbahar", ImageUrls = "dantel.jpg", DateAdded = DateTime.Now.ToString() },
                new Product { ProductId = 79, Color = "Kahverengi", Cut = "Cargo", Name = "Şort", Price = 29.99, CurrencyType = "TRY", Description = "Pratik şort", CategoryID = 9, BrandID = 8, Gender = "Erkek", Material = "Kanvas", Style = "Günlük", Season = "Yaz", ImageUrls = "sort.jpg", DateAdded = DateTime.Now.ToString() },
                new Product { ProductId = 80, Color = "Yeşil", Cut = "Uzun", Name = "Pijama Takımı", Price = 49.99, CurrencyType = "TRY", Description = "Pamuklu pijama takımı", CategoryID = 11, BrandID = 7, Gender = "Unisex", Material = "Pamuk", Style = "Rahat", Season = "Kış", ImageUrls = "pijama.jpg", DateAdded = DateTime.Now.ToString() },
                new Product { ProductId = 81, Color = "Lacivert", Cut = "Slim-fit", Name = "Takım Elbise", Price = 299.99, CurrencyType = "TRY", Description = "Yün takım elbise", CategoryID = 7, BrandID = 14, Gender = "Erkek", Material = "Yün", Style = "Formal", Season = "All-season", ImageUrls = "takim.jpg", DateAdded = DateTime.Now.ToString() },
                new Product { ProductId = 83, Color = "Kırmızı", Cut = "Düz", Name = "Kot Pantolon", Price = 69.99, CurrencyType = "TRY", Description = "Kırmızı kot pantolon", CategoryID = 1, BrandID = 3, Gender = "Kadın", Material = "Denim", Style = "Cesur", Season = "All-season", ImageUrls = "pantolon.jpg", DateAdded = DateTime.Now.ToString() },
                new Product { ProductId = 84, Color = "Bordo", Cut = "Slim-fit", Name = "Tişört", Price = 29.99, CurrencyType = "TRY", Description = "Bordo tişört", CategoryID = 3, BrandID = 16, Gender = "Erkek", Material = "Pamuk", Style = "Spor", Season = "Yaz", ImageUrls = "tisort.jpg", DateAdded = DateTime.Now.ToString() },
                new Product { ProductId = 85, Color = "Bej", Cut = "Midi", Name = "Etek", Price = 39.99, CurrencyType = "TRY", Description = "Bej etek", CategoryID = 4, BrandID = 9, Gender = "Kadın", Material = "Keten", Style = "Günlük", Season = "İlkbahar", ImageUrls = "etek.jpg", DateAdded = DateTime.Now.ToString() },
                new Product { ProductId = 86, Color = "Siyah", Cut = "Oversize", Name = "Kapüşonlu", Price = 49.99, CurrencyType = "TRY", Description = "Siyah kapüşonlu", CategoryID = 6, BrandID = 1, Gender = "Unisex", Material = "Pamuk", Style = "Casual", Season = "Sonbahar", ImageUrls = "kapusonlu.jpg", DateAdded = DateTime.Now.ToString() },
                new Product { ProductId = 87, Color = "Mavi", Cut = "Trench", Name = "Mont", Price = 99.99, CurrencyType = "TRY", Description = "Mavi mont", CategoryID = 8, BrandID = 6, Gender = "Erkek", Material = "Naylon", Style = "Şık", Season = "Kış", ImageUrls = "mont.jpg", DateAdded = DateTime.Now.ToString() },
                new Product { ProductId = 88, Color = "Pembe", Cut = "Şort", Name = "Pijama", Price = 34.99, CurrencyType = "TRY", Description = "Pembe pijama", CategoryID = 11, BrandID = 5, Gender = "Kadın", Material = "Pamuk", Style = "Rahat", Season = "Yaz", ImageUrls = "pijama.jpg", DateAdded = DateTime.Now.ToString() },
                new Product { ProductId = 89, Color = "Turuncu", Cut = "Dar", Name = "Çopap", Price = 19.99, CurrencyType = "TRY", Description = "Turuncu çopap", CategoryID = 10, BrandID = 7, Gender = "Kadın", Material = "Likra", Style = "Spor", Season = "All-season", ImageUrls = "copap.jpg", DateAdded = DateTime.Now.ToString() },
                new Product { ProductId = 90, Color = "Mor", Cut = "Uzun", Name = "Elbise", Price = 59.99, CurrencyType = "TRY", Description = "Mor elbise", CategoryID = 5, BrandID = 10, Gender = "Kadın", Material = "Viskon", Style = "Şık", Season = "İlkbahar", ImageUrls = "elbise.jpg", DateAdded = DateTime.Now.ToString() },
                new Product { ProductId = 91, Color = "Kahverengi", Cut = "Regular", Name = "Ceket", Price = 149.99, CurrencyType = "TRY", Description = "Kahverengi ceket", CategoryID = 7, BrandID = 13, Gender = "Erkek", Material = "Deri", Style = "Rock", Season = "All-season", ImageUrls = "ceket.jpg", DateAdded = DateTime.Now.ToString() },
                new Product { ProductId = 92, Color = "Yeşil", Cut = "Kısa", Name = "Şort", Price = 24.99, CurrencyType = "TRY", Description = "Yeşil şort", CategoryID = 9, BrandID = 8, Gender = "Erkek", Material = "Pamuk", Style = "Günlük", Season = "Yaz", ImageUrls = "sort.jpg", DateAdded = DateTime.Now.ToString() },
                new Product { ProductId = 93, Color = "Lacivert", Cut = "Skinny", Name = "Tayt", Price = 29.99, CurrencyType = "TRY", Description = "Lacivert tayt", CategoryID = 10, BrandID = 16, Gender = "Kadın", Material = "Elastan", Style = "Spor", Season = "All-season", ImageUrls = "tayt.jpg", DateAdded = DateTime.Now.ToString() },
                new Product { ProductId = 94, Color = "Sarı", Cut = "Slim-fit", Name = "Gömlek", Price = 44.99, CurrencyType = "TRY", Description = "Sarı gömlek", CategoryID = 2, BrandID = 12, Gender = "Erkek", Material = "Pamuk", Style = "Formal", Season = "Yaz", ImageUrls = "gomlek.jpg", DateAdded = DateTime.Now.ToString() },
                new Product { ProductId = 95, Color = "Bordo", Cut = "Maxi", Name = "Etek", Price = 49.99, CurrencyType = "TRY", Description = "Bordo etek", CategoryID = 4, BrandID = 11, Gender = "Kadın", Material = "Keten", Style = "Bohem", Season = "Yaz", ImageUrls = "etek.jpg", DateAdded = DateTime.Now.ToString() },
                new Product { ProductId = 96, Color = "Bej", Cut = "Oversize", Name = "Kazak", Price = 39.99, CurrencyType = "TRY", Description = "Bej kazak", CategoryID = 6, BrandID = 9, Gender = "Unisex", Material = "Akrilik", Style = "Casual", Season = "Kış", ImageUrls = "kazak.jpg", DateAdded = DateTime.Now.ToString() },
                new Product { ProductId = 97, Color = "Siyah", Cut = "Parka", Name = "Mont", Price = 119.99, CurrencyType = "TRY", Description = "Siyah mont", CategoryID = 8, BrandID = 6, Gender = "Unisex", Material = "Polar", Style = "Sıcak", Season = "Kış", ImageUrls = "mont.jpg", DateAdded = DateTime.Now.ToString() },
                new Product { ProductId = 98, Color = "Mavi", Cut = "Uzun", Name = "Pijama", Price = 54.99, CurrencyType = "TRY", Description = "Mavi pijama", CategoryID = 11, BrandID = 7, Gender = "Unisex", Material = "Pamuk", Style = "Rahat", Season = "Kış", ImageUrls = "pijama.jpg", DateAdded = DateTime.Now.ToString() },
                new Product { ProductId = 99, Color = "Pembe", Cut = "Dar", Name = "Çopap", Price = 14.99, CurrencyType = "TRY", Description = "Pembe çopap", CategoryID = 10, BrandID = 5, Gender = "Kadın", Material = "Likra", Style = "Spor", Season = "All-season", ImageUrls = "copap.jpg", DateAdded = DateTime.Now.ToString() },
                new Product { ProductId = 100, Color = "Turuncu", Cut = "Mini", Name = "Elbise", Price = 64.99, CurrencyType = "TRY", Description = "Turuncu elbise", CategoryID = 5, BrandID = 4, Gender = "Kadın", Material = "Viskon", Style = "Cesur", Season = "Yaz", ImageUrls = "elbise.jpg", DateAdded = DateTime.Now.ToString() },
                new Product { ProductId = 101, Color = "Mor", Cut = "Regular", Name = "Ceket", Price = 169.99, CurrencyType = "TRY", Description = "Mor ceket", CategoryID = 7, BrandID = 13, Gender = "Erkek", Material = "Yün", Style = "Şık", Season = "All-season", ImageUrls = "ceket.jpg", DateAdded = DateTime.Now.ToString() }
                
            );

            modelBuilder.Entity<ProductStock>().HasData(
                new ProductStock { ProductStockId = 1, ProductId = 1, Size = "L", StockQuantity = 50 },
new ProductStock { ProductStockId = 2, ProductId = 1, Size = "XL", StockQuantity = 18 },
new ProductStock { ProductStockId = 3, ProductId = 1, Size = "S", StockQuantity = 28 },
new ProductStock { ProductStockId = 4, ProductId = 1, Size = "XS", StockQuantity = 49 },
new ProductStock { ProductStockId = 5, ProductId = 2, Size = "S", StockQuantity = 32 },
new ProductStock { ProductStockId = 6, ProductId = 2, Size = "L", StockQuantity = 21 },
new ProductStock { ProductStockId = 7, ProductId = 2, Size = "M", StockQuantity = 28 },
new ProductStock { ProductStockId = 8, ProductId = 2, Size = "XS", StockQuantity = 41 },
new ProductStock { ProductStockId = 9, ProductId = 3, Size = "S", StockQuantity = 6 },
new ProductStock { ProductStockId = 10, ProductId = 3, Size = "M", StockQuantity = 44 },
new ProductStock { ProductStockId = 11, ProductId = 3, Size = "XS", StockQuantity = 32 },
new ProductStock { ProductStockId = 12, ProductId = 3, Size = "XL", StockQuantity = 34 },
new ProductStock { ProductStockId = 13, ProductId = 4, Size = "S", StockQuantity = 6 },
new ProductStock { ProductStockId = 14, ProductId = 4, Size = "XS", StockQuantity = 32 },
new ProductStock { ProductStockId = 15, ProductId = 4, Size = "XL", StockQuantity = 50 },
new ProductStock { ProductStockId = 16, ProductId = 4, Size = "M", StockQuantity = 24 },
new ProductStock { ProductStockId = 17, ProductId = 5, Size = "XS", StockQuantity = 11 },
new ProductStock { ProductStockId = 18, ProductId = 5, Size = "XL", StockQuantity = 18 },
new ProductStock { ProductStockId = 19, ProductId = 5, Size = "S", StockQuantity = 40 },
new ProductStock { ProductStockId = 20, ProductId = 5, Size = "L", StockQuantity = 28 },
new ProductStock { ProductStockId = 21, ProductId = 6, Size = "L", StockQuantity = 47 },
new ProductStock { ProductStockId = 22, ProductId = 6, Size = "XL", StockQuantity = 48 },
new ProductStock { ProductStockId = 23, ProductId = 6, Size = "S", StockQuantity = 7 },
new ProductStock { ProductStockId = 24, ProductId = 6, Size = "M", StockQuantity = 6 },
new ProductStock { ProductStockId = 25, ProductId = 7, Size = "M", StockQuantity = 27 },
new ProductStock { ProductStockId = 26, ProductId = 7, Size = "S", StockQuantity = 39 },
new ProductStock { ProductStockId = 27, ProductId = 7, Size = "L", StockQuantity = 50 },
new ProductStock { ProductStockId = 28, ProductId = 7, Size = "XL", StockQuantity = 19 },
new ProductStock { ProductStockId = 29, ProductId = 8, Size = "S", StockQuantity = 16 },
new ProductStock { ProductStockId = 30, ProductId = 8, Size = "XS", StockQuantity = 35 },
new ProductStock { ProductStockId = 31, ProductId = 8, Size = "L", StockQuantity = 11 },
new ProductStock { ProductStockId = 32, ProductId = 8, Size = "M", StockQuantity = 38 },
new ProductStock { ProductStockId = 33, ProductId = 9, Size = "L", StockQuantity = 30 },
new ProductStock { ProductStockId = 34, ProductId = 9, Size = "S", StockQuantity = 36 },
new ProductStock { ProductStockId = 35, ProductId = 9, Size = "XL", StockQuantity = 6 },
new ProductStock { ProductStockId = 36, ProductId = 9, Size = "M", StockQuantity = 43 },
new ProductStock { ProductStockId = 37, ProductId = 10, Size = "XL", StockQuantity = 11 },
new ProductStock { ProductStockId = 38, ProductId = 10, Size = "XS", StockQuantity = 40 },
new ProductStock { ProductStockId = 39, ProductId = 10, Size = "M", StockQuantity = 21 },
new ProductStock { ProductStockId = 40, ProductId = 10, Size = "S", StockQuantity = 48 },
new ProductStock { ProductStockId = 41, ProductId = 11, Size = "L", StockQuantity = 6 },
new ProductStock { ProductStockId = 42, ProductId = 11, Size = "M", StockQuantity = 40 },
new ProductStock { ProductStockId = 43, ProductId = 11, Size = "XS", StockQuantity = 19 },
new ProductStock { ProductStockId = 44, ProductId = 11, Size = "XL", StockQuantity = 49 },
new ProductStock { ProductStockId = 45, ProductId = 12, Size = "S", StockQuantity = 19 },
new ProductStock { ProductStockId = 46, ProductId = 12, Size = "XS", StockQuantity = 35 },
new ProductStock { ProductStockId = 47, ProductId = 12, Size = "M", StockQuantity = 14 },
new ProductStock { ProductStockId = 48, ProductId = 12, Size = "L", StockQuantity = 10 },
new ProductStock { ProductStockId = 49, ProductId = 13, Size = "XS", StockQuantity = 48 },
new ProductStock { ProductStockId = 50, ProductId = 13, Size = "L", StockQuantity = 48 },
new ProductStock { ProductStockId = 51, ProductId = 13, Size = "XL", StockQuantity = 14 },
new ProductStock { ProductStockId = 52, ProductId = 13, Size = "M", StockQuantity = 38 },
new ProductStock { ProductStockId = 53, ProductId = 14, Size = "S", StockQuantity = 42 },
new ProductStock { ProductStockId = 54, ProductId = 14, Size = "M", StockQuantity = 44 },
new ProductStock { ProductStockId = 55, ProductId = 14, Size = "L", StockQuantity = 47 },
new ProductStock { ProductStockId = 56, ProductId = 14, Size = "XL", StockQuantity = 24 },
new ProductStock { ProductStockId = 57, ProductId = 15, Size = "S", StockQuantity = 39 },
new ProductStock { ProductStockId = 58, ProductId = 15, Size = "XL", StockQuantity = 30 },
new ProductStock { ProductStockId = 59, ProductId = 15, Size = "M", StockQuantity = 46 },
new ProductStock { ProductStockId = 60, ProductId = 15, Size = "L", StockQuantity = 45 },
new ProductStock { ProductStockId = 61, ProductId = 16, Size = "S", StockQuantity = 25 },
new ProductStock { ProductStockId = 62, ProductId = 16, Size = "XS", StockQuantity = 15 },
new ProductStock { ProductStockId = 63, ProductId = 16, Size = "L", StockQuantity = 38 },
new ProductStock { ProductStockId = 64, ProductId = 16, Size = "XL", StockQuantity = 5 },
new ProductStock { ProductStockId = 65, ProductId = 17, Size = "XS", StockQuantity = 17 },
new ProductStock { ProductStockId = 66, ProductId = 17, Size = "S", StockQuantity = 14 },
new ProductStock { ProductStockId = 67, ProductId = 17, Size = "XL", StockQuantity = 35 },
new ProductStock { ProductStockId = 68, ProductId = 17, Size = "M", StockQuantity = 48 },
new ProductStock { ProductStockId = 69, ProductId = 18, Size = "S", StockQuantity = 19 },
new ProductStock { ProductStockId = 70, ProductId = 18, Size = "L", StockQuantity = 32 },
new ProductStock { ProductStockId = 71, ProductId = 18, Size = "M", StockQuantity = 37 },
new ProductStock { ProductStockId = 72, ProductId = 18, Size = "XS", StockQuantity = 21 },
new ProductStock { ProductStockId = 73, ProductId = 19, Size = "M", StockQuantity = 41 },
new ProductStock { ProductStockId = 74, ProductId = 19, Size = "S", StockQuantity = 15 },
new ProductStock { ProductStockId = 75, ProductId = 19, Size = "XS", StockQuantity = 28 },
new ProductStock { ProductStockId = 76, ProductId = 19, Size = "XL", StockQuantity = 16 },
new ProductStock { ProductStockId = 77, ProductId = 20, Size = "M", StockQuantity = 24 },
new ProductStock { ProductStockId = 78, ProductId = 20, Size = "XS", StockQuantity = 39 },
new ProductStock { ProductStockId = 79, ProductId = 20, Size = "L", StockQuantity = 6 },
new ProductStock { ProductStockId = 80, ProductId = 20, Size = "S", StockQuantity = 25 },
new ProductStock { ProductStockId = 81, ProductId = 21, Size = "XL", StockQuantity = 47 },
new ProductStock { ProductStockId = 82, ProductId = 21, Size = "M", StockQuantity = 10 },
new ProductStock { ProductStockId = 83, ProductId = 21, Size = "S", StockQuantity = 29 },
new ProductStock { ProductStockId = 84, ProductId = 21, Size = "XS", StockQuantity = 16 },
new ProductStock { ProductStockId = 85, ProductId = 22, Size = "S", StockQuantity = 16 },
new ProductStock { ProductStockId = 86, ProductId = 22, Size = "L", StockQuantity = 47 },
new ProductStock { ProductStockId = 87, ProductId = 22, Size = "M", StockQuantity = 39 },
new ProductStock { ProductStockId = 88, ProductId = 22, Size = "XS", StockQuantity = 50 },
new ProductStock { ProductStockId = 89, ProductId = 23, Size = "XS", StockQuantity = 19 },
new ProductStock { ProductStockId = 90, ProductId = 23, Size = "M", StockQuantity = 14 },
new ProductStock { ProductStockId = 91, ProductId = 23, Size = "S", StockQuantity = 32 },
new ProductStock { ProductStockId = 92, ProductId = 23, Size = "L", StockQuantity = 10 },
new ProductStock { ProductStockId = 93, ProductId = 24, Size = "L", StockQuantity = 7 },
new ProductStock { ProductStockId = 94, ProductId = 24, Size = "XL", StockQuantity = 20 },
new ProductStock { ProductStockId = 95, ProductId = 24, Size = "XS", StockQuantity = 20 },
new ProductStock { ProductStockId = 96, ProductId = 24, Size = "S", StockQuantity = 25 },
new ProductStock { ProductStockId = 97, ProductId = 25, Size = "S", StockQuantity = 32 },
new ProductStock { ProductStockId = 98, ProductId = 25, Size = "M", StockQuantity = 21 },
new ProductStock { ProductStockId = 99, ProductId = 25, Size = "XS", StockQuantity = 21 },
new ProductStock { ProductStockId = 100, ProductId = 25, Size = "L", StockQuantity = 47 },
new ProductStock { ProductStockId = 101, ProductId = 26, Size = "XL", StockQuantity = 24 },
new ProductStock { ProductStockId = 102, ProductId = 26, Size = "M", StockQuantity = 21 },
new ProductStock { ProductStockId = 103, ProductId = 26, Size = "XS", StockQuantity = 9 },
new ProductStock { ProductStockId = 104, ProductId = 26, Size = "L", StockQuantity = 42 },
new ProductStock { ProductStockId = 105, ProductId = 27, Size = "M", StockQuantity = 50 },
new ProductStock { ProductStockId = 106, ProductId = 27, Size = "XS", StockQuantity = 25 },
new ProductStock { ProductStockId = 107, ProductId = 27, Size = "XL", StockQuantity = 25 },
new ProductStock { ProductStockId = 108, ProductId = 27, Size = "L", StockQuantity = 30 },
new ProductStock { ProductStockId = 109, ProductId = 28, Size = "XS", StockQuantity = 46 },
new ProductStock { ProductStockId = 110, ProductId = 28, Size = "S", StockQuantity = 9 },
new ProductStock { ProductStockId = 111, ProductId = 28, Size = "L", StockQuantity = 8 },
new ProductStock { ProductStockId = 112, ProductId = 28, Size = "XL", StockQuantity = 44 },
new ProductStock { ProductStockId = 113, ProductId = 29, Size = "M", StockQuantity = 49 },
new ProductStock { ProductStockId = 114, ProductId = 29, Size = "L", StockQuantity = 15 },
new ProductStock { ProductStockId = 115, ProductId = 29, Size = "S", StockQuantity = 46 },
new ProductStock { ProductStockId = 116, ProductId = 29, Size = "XS", StockQuantity = 5 },
new ProductStock { ProductStockId = 117, ProductId = 30, Size = "M", StockQuantity = 12 },
new ProductStock { ProductStockId = 118, ProductId = 30, Size = "XL", StockQuantity = 25 },
new ProductStock { ProductStockId = 119, ProductId = 30, Size = "S", StockQuantity = 25 },
new ProductStock { ProductStockId = 120, ProductId = 30, Size = "L", StockQuantity = 19 },
new ProductStock { ProductStockId = 121, ProductId = 31, Size = "L", StockQuantity = 50 },
new ProductStock { ProductStockId = 122, ProductId = 31, Size = "S", StockQuantity = 20 },
new ProductStock { ProductStockId = 123, ProductId = 31, Size = "XS", StockQuantity = 5 },
new ProductStock { ProductStockId = 124, ProductId = 31, Size = "XL", StockQuantity = 28 },
new ProductStock { ProductStockId = 125, ProductId = 32, Size = "XL", StockQuantity = 28 },
new ProductStock { ProductStockId = 126, ProductId = 32, Size = "M", StockQuantity = 37 },
new ProductStock { ProductStockId = 127, ProductId = 32, Size = "L", StockQuantity = 25 },
new ProductStock { ProductStockId = 128, ProductId = 32, Size = "S", StockQuantity = 33 },
new ProductStock { ProductStockId = 129, ProductId = 33, Size = "L", StockQuantity = 14 },
new ProductStock { ProductStockId = 130, ProductId = 33, Size = "XL", StockQuantity = 16 },
new ProductStock { ProductStockId = 131, ProductId = 33, Size = "M", StockQuantity = 16 },
new ProductStock { ProductStockId = 132, ProductId = 33, Size = "S", StockQuantity = 45 },
new ProductStock { ProductStockId = 133, ProductId = 34, Size = "XL", StockQuantity = 18 },
new ProductStock { ProductStockId = 134, ProductId = 34, Size = "XS", StockQuantity = 31 },
new ProductStock { ProductStockId = 135, ProductId = 34, Size = "S", StockQuantity = 50 },
new ProductStock { ProductStockId = 136, ProductId = 34, Size = "M", StockQuantity = 36 },
new ProductStock { ProductStockId = 137, ProductId = 35, Size = "L", StockQuantity = 15 },
new ProductStock { ProductStockId = 138, ProductId = 35, Size = "XL", StockQuantity = 19 },
new ProductStock { ProductStockId = 139, ProductId = 35, Size = "XS", StockQuantity = 26 },
new ProductStock { ProductStockId = 140, ProductId = 35, Size = "M", StockQuantity = 37 },
new ProductStock { ProductStockId = 141, ProductId = 36, Size = "M", StockQuantity = 44 },
new ProductStock { ProductStockId = 142, ProductId = 36, Size = "XL", StockQuantity = 13 },
new ProductStock { ProductStockId = 143, ProductId = 36, Size = "XS", StockQuantity = 44 },
new ProductStock { ProductStockId = 144, ProductId = 36, Size = "S", StockQuantity = 31 },
new ProductStock { ProductStockId = 145, ProductId = 37, Size = "XL", StockQuantity = 11 },
new ProductStock { ProductStockId = 146, ProductId = 37, Size = "L", StockQuantity = 30 },
new ProductStock { ProductStockId = 147, ProductId = 37, Size = "S", StockQuantity = 6 },
new ProductStock { ProductStockId = 148, ProductId = 37, Size = "M", StockQuantity = 18 },
new ProductStock { ProductStockId = 149, ProductId = 38, Size = "M", StockQuantity = 9 },
new ProductStock { ProductStockId = 150, ProductId = 38, Size = "S", StockQuantity = 35 },
new ProductStock { ProductStockId = 151, ProductId = 38, Size = "XL", StockQuantity = 10 },
new ProductStock { ProductStockId = 152, ProductId = 38, Size = "XS", StockQuantity = 17 },
new ProductStock { ProductStockId = 153, ProductId = 39, Size = "XS", StockQuantity = 45 },
new ProductStock { ProductStockId = 154, ProductId = 39, Size = "M", StockQuantity = 42 },
new ProductStock { ProductStockId = 155, ProductId = 39, Size = "S", StockQuantity = 19 },
new ProductStock { ProductStockId = 156, ProductId = 39, Size = "L", StockQuantity = 8 },
new ProductStock { ProductStockId = 157, ProductId = 40, Size = "M", StockQuantity = 6 },
new ProductStock { ProductStockId = 158, ProductId = 40, Size = "S", StockQuantity = 40 },
new ProductStock { ProductStockId = 159, ProductId = 40, Size = "XL", StockQuantity = 50 },
new ProductStock { ProductStockId = 160, ProductId = 40, Size = "L", StockQuantity = 13 },
new ProductStock { ProductStockId = 161, ProductId = 41, Size = "M", StockQuantity = 31 },
new ProductStock { ProductStockId = 162, ProductId = 41, Size = "S", StockQuantity = 10 },
new ProductStock { ProductStockId = 163, ProductId = 41, Size = "XS", StockQuantity = 7 },
new ProductStock { ProductStockId = 164, ProductId = 41, Size = "L", StockQuantity = 36 },
new ProductStock { ProductStockId = 165, ProductId = 42, Size = "M", StockQuantity = 5 },
new ProductStock { ProductStockId = 166, ProductId = 42, Size = "XL", StockQuantity = 40 },
new ProductStock { ProductStockId = 167, ProductId = 42, Size = "S", StockQuantity = 14 },
new ProductStock { ProductStockId = 168, ProductId = 42, Size = "L", StockQuantity = 14 },
new ProductStock { ProductStockId = 169, ProductId = 43, Size = "M", StockQuantity = 34 },
new ProductStock { ProductStockId = 170, ProductId = 43, Size = "L", StockQuantity = 20 },
new ProductStock { ProductStockId = 171, ProductId = 43, Size = "S", StockQuantity = 42 },
new ProductStock { ProductStockId = 172, ProductId = 43, Size = "XL", StockQuantity = 13 },
new ProductStock { ProductStockId = 173, ProductId = 44, Size = "S", StockQuantity = 15 },
new ProductStock { ProductStockId = 174, ProductId = 44, Size = "XL", StockQuantity = 19 },
new ProductStock { ProductStockId = 175, ProductId = 44, Size = "M", StockQuantity = 34 },
new ProductStock { ProductStockId = 176, ProductId = 44, Size = "L", StockQuantity = 47 },
new ProductStock { ProductStockId = 177, ProductId = 45, Size = "XL", StockQuantity = 16 },
new ProductStock { ProductStockId = 178, ProductId = 45, Size = "S", StockQuantity = 33 },
new ProductStock { ProductStockId = 179, ProductId = 45, Size = "XS", StockQuantity = 35 },
new ProductStock { ProductStockId = 180, ProductId = 45, Size = "M", StockQuantity = 50 },
new ProductStock { ProductStockId = 181, ProductId = 46, Size = "XL", StockQuantity = 10 },
new ProductStock { ProductStockId = 182, ProductId = 46, Size = "L", StockQuantity = 28 },
new ProductStock { ProductStockId = 183, ProductId = 46, Size = "XS", StockQuantity = 44 },
new ProductStock { ProductStockId = 184, ProductId = 46, Size = "M", StockQuantity = 28 },
new ProductStock { ProductStockId = 185, ProductId = 47, Size = "M", StockQuantity = 39 },
new ProductStock { ProductStockId = 186, ProductId = 47, Size = "L", StockQuantity = 42 },
new ProductStock { ProductStockId = 187, ProductId = 47, Size = "XL", StockQuantity = 9 },
new ProductStock { ProductStockId = 188, ProductId = 47, Size = "XS", StockQuantity = 5 },
new ProductStock { ProductStockId = 189, ProductId = 48, Size = "XS", StockQuantity = 9 },
new ProductStock { ProductStockId = 190, ProductId = 48, Size = "XL", StockQuantity = 34 },
new ProductStock { ProductStockId = 191, ProductId = 48, Size = "L", StockQuantity = 37 },
new ProductStock { ProductStockId = 192, ProductId = 48, Size = "M", StockQuantity = 35 },
new ProductStock { ProductStockId = 193, ProductId = 49, Size = "L", StockQuantity = 11 },
new ProductStock { ProductStockId = 194, ProductId = 49, Size = "XS", StockQuantity = 35 },
new ProductStock { ProductStockId = 195, ProductId = 49, Size = "M", StockQuantity = 45 },
new ProductStock { ProductStockId = 196, ProductId = 49, Size = "XL", StockQuantity = 29 },
new ProductStock { ProductStockId = 197, ProductId = 50, Size = "XL", StockQuantity = 46 },
new ProductStock { ProductStockId = 198, ProductId = 50, Size = "XS", StockQuantity = 46 },
new ProductStock { ProductStockId = 199, ProductId = 50, Size = "S", StockQuantity = 18 },
new ProductStock { ProductStockId = 200, ProductId = 50, Size = "M", StockQuantity = 17 },
new ProductStock { ProductStockId = 201, ProductId = 51, Size = "M", StockQuantity = 8 },
new ProductStock { ProductStockId = 202, ProductId = 51, Size = "L", StockQuantity = 17 },
new ProductStock { ProductStockId = 203, ProductId = 51, Size = "XS", StockQuantity = 16 },
new ProductStock { ProductStockId = 204, ProductId = 51, Size = "S", StockQuantity = 44 },
new ProductStock { ProductStockId = 205, ProductId = 52, Size = "XS", StockQuantity = 39 },
new ProductStock { ProductStockId = 206, ProductId = 52, Size = "S", StockQuantity = 7 },
new ProductStock { ProductStockId = 207, ProductId = 52, Size = "XL", StockQuantity = 30 },
new ProductStock { ProductStockId = 208, ProductId = 52, Size = "L", StockQuantity = 46 },
new ProductStock { ProductStockId = 209, ProductId = 53, Size = "XL", StockQuantity = 5 },
new ProductStock { ProductStockId = 210, ProductId = 53, Size = "L", StockQuantity = 15 },
new ProductStock { ProductStockId = 211, ProductId = 53, Size = "XS", StockQuantity = 20 },
new ProductStock { ProductStockId = 212, ProductId = 53, Size = "M", StockQuantity = 7 },
new ProductStock { ProductStockId = 213, ProductId = 54, Size = "XS", StockQuantity = 38 },
new ProductStock { ProductStockId = 214, ProductId = 54, Size = "M", StockQuantity = 42 },
new ProductStock { ProductStockId = 215, ProductId = 54, Size = "L", StockQuantity = 17 },
new ProductStock { ProductStockId = 216, ProductId = 54, Size = "XL", StockQuantity = 22 },
new ProductStock { ProductStockId = 217, ProductId = 55, Size = "M", StockQuantity = 47 },
new ProductStock { ProductStockId = 218, ProductId = 55, Size = "S", StockQuantity = 15 },
new ProductStock { ProductStockId = 219, ProductId = 55, Size = "L", StockQuantity = 50 },
new ProductStock { ProductStockId = 220, ProductId = 55, Size = "XL", StockQuantity = 20 },
new ProductStock { ProductStockId = 221, ProductId = 56, Size = "XS", StockQuantity = 8 },
new ProductStock { ProductStockId = 222, ProductId = 56, Size = "M", StockQuantity = 8 },
new ProductStock { ProductStockId = 223, ProductId = 56, Size = "L", StockQuantity = 17 },
new ProductStock { ProductStockId = 224, ProductId = 56, Size = "S", StockQuantity = 40 },
new ProductStock { ProductStockId = 225, ProductId = 57, Size = "XS", StockQuantity = 20 },
new ProductStock { ProductStockId = 226, ProductId = 57, Size = "M", StockQuantity = 17 },
new ProductStock { ProductStockId = 227, ProductId = 57, Size = "L", StockQuantity = 31 },
new ProductStock { ProductStockId = 228, ProductId = 57, Size = "S", StockQuantity = 28 },
new ProductStock { ProductStockId = 229, ProductId = 58, Size = "M", StockQuantity = 34 },
new ProductStock { ProductStockId = 230, ProductId = 58, Size = "S", StockQuantity = 9 },
new ProductStock { ProductStockId = 231, ProductId = 58, Size = "XS", StockQuantity = 26 },
new ProductStock { ProductStockId = 232, ProductId = 58, Size = "XL", StockQuantity = 44 },
new ProductStock { ProductStockId = 233, ProductId = 59, Size = "XL", StockQuantity = 43 },
new ProductStock { ProductStockId = 234, ProductId = 59, Size = "M", StockQuantity = 20 },
new ProductStock { ProductStockId = 235, ProductId = 59, Size = "L", StockQuantity = 25 },
new ProductStock { ProductStockId = 236, ProductId = 59, Size = "XS", StockQuantity = 17 },
new ProductStock { ProductStockId = 237, ProductId = 60, Size = "L", StockQuantity = 34 },
new ProductStock { ProductStockId = 238, ProductId = 60, Size = "XS", StockQuantity = 38 },
new ProductStock { ProductStockId = 239, ProductId = 60, Size = "S", StockQuantity = 6 },
new ProductStock { ProductStockId = 240, ProductId = 60, Size = "XL", StockQuantity = 16 },
new ProductStock { ProductStockId = 241, ProductId = 61, Size = "S", StockQuantity = 5 },
new ProductStock { ProductStockId = 242, ProductId = 61, Size = "L", StockQuantity = 15 },
new ProductStock { ProductStockId = 243, ProductId = 61, Size = "M", StockQuantity = 23 },
new ProductStock { ProductStockId = 244, ProductId = 61, Size = "XL", StockQuantity = 11 },
new ProductStock { ProductStockId = 245, ProductId = 62, Size = "S", StockQuantity = 33 },
new ProductStock { ProductStockId = 246, ProductId = 62, Size = "L", StockQuantity = 22 },
new ProductStock { ProductStockId = 247, ProductId = 62, Size = "M", StockQuantity = 43 },
new ProductStock { ProductStockId = 248, ProductId = 62, Size = "XL", StockQuantity = 41 },
new ProductStock { ProductStockId = 249, ProductId = 63, Size = "L", StockQuantity = 32 },
new ProductStock { ProductStockId = 250, ProductId = 63, Size = "M", StockQuantity = 28 },
new ProductStock { ProductStockId = 251, ProductId = 63, Size = "XS", StockQuantity = 49 },
new ProductStock { ProductStockId = 252, ProductId = 63, Size = "S", StockQuantity = 31 },
new ProductStock { ProductStockId = 253, ProductId = 64, Size = "XL", StockQuantity = 13 },
new ProductStock { ProductStockId = 254, ProductId = 64, Size = "M", StockQuantity = 14 },
new ProductStock { ProductStockId = 255, ProductId = 64, Size = "L", StockQuantity = 35 },
new ProductStock { ProductStockId = 256, ProductId = 64, Size = "XS", StockQuantity = 31 },
new ProductStock { ProductStockId = 257, ProductId = 65, Size = "M", StockQuantity = 34 },
new ProductStock { ProductStockId = 258, ProductId = 65, Size = "L", StockQuantity = 40 },
new ProductStock { ProductStockId = 259, ProductId = 65, Size = "S", StockQuantity = 23 },
new ProductStock { ProductStockId = 260, ProductId = 65, Size = "XL", StockQuantity = 28 },
new ProductStock { ProductStockId = 261, ProductId = 66, Size = "L", StockQuantity = 21 },
new ProductStock { ProductStockId = 262, ProductId = 66, Size = "M", StockQuantity = 12 },
new ProductStock { ProductStockId = 263, ProductId = 66, Size = "XS", StockQuantity = 40 },
new ProductStock { ProductStockId = 264, ProductId = 66, Size = "XL", StockQuantity = 20 },
new ProductStock { ProductStockId = 265, ProductId = 67, Size = "XS", StockQuantity = 48 },
new ProductStock { ProductStockId = 266, ProductId = 67, Size = "S", StockQuantity = 13 },
new ProductStock { ProductStockId = 267, ProductId = 67, Size = "XL", StockQuantity = 40 },
new ProductStock { ProductStockId = 268, ProductId = 67, Size = "M", StockQuantity = 5 },
new ProductStock { ProductStockId = 269, ProductId = 68, Size = "L", StockQuantity = 5 },
new ProductStock { ProductStockId = 270, ProductId = 68, Size = "S", StockQuantity = 22 },
new ProductStock { ProductStockId = 271, ProductId = 68, Size = "M", StockQuantity = 40 },
new ProductStock { ProductStockId = 272, ProductId = 68, Size = "XS", StockQuantity = 44 },
new ProductStock { ProductStockId = 273, ProductId = 69, Size = "XL", StockQuantity = 9 },
new ProductStock { ProductStockId = 274, ProductId = 69, Size = "S", StockQuantity = 17 },
new ProductStock { ProductStockId = 275, ProductId = 69, Size = "XS", StockQuantity = 9 },
new ProductStock { ProductStockId = 276, ProductId = 69, Size = "L", StockQuantity = 48 },
new ProductStock { ProductStockId = 277, ProductId = 70, Size = "XL", StockQuantity = 8 },
new ProductStock { ProductStockId = 278, ProductId = 70, Size = "S", StockQuantity = 41 },
new ProductStock { ProductStockId = 279, ProductId = 70, Size = "M", StockQuantity = 50 },
new ProductStock { ProductStockId = 280, ProductId = 70, Size = "L", StockQuantity = 20 },
new ProductStock { ProductStockId = 281, ProductId = 71, Size = "XS", StockQuantity = 29 },
new ProductStock { ProductStockId = 282, ProductId = 71, Size = "M", StockQuantity = 40 },
new ProductStock { ProductStockId = 283, ProductId = 71, Size = "L", StockQuantity = 37 },
new ProductStock { ProductStockId = 284, ProductId = 71, Size = "S", StockQuantity = 27 },
new ProductStock { ProductStockId = 285, ProductId = 72, Size = "M", StockQuantity = 45 },
new ProductStock { ProductStockId = 286, ProductId = 72, Size = "XL", StockQuantity = 20 },
new ProductStock { ProductStockId = 287, ProductId = 72, Size = "L", StockQuantity = 20 },
new ProductStock { ProductStockId = 288, ProductId = 72, Size = "XS", StockQuantity = 48 },
new ProductStock { ProductStockId = 289, ProductId = 73, Size = "XS", StockQuantity = 21 },
new ProductStock { ProductStockId = 290, ProductId = 73, Size = "L", StockQuantity = 7 },
new ProductStock { ProductStockId = 291, ProductId = 73, Size = "XL", StockQuantity = 5 },
new ProductStock { ProductStockId = 292, ProductId = 73, Size = "M", StockQuantity = 37 },
new ProductStock { ProductStockId = 293, ProductId = 74, Size = "M", StockQuantity = 10 },
new ProductStock { ProductStockId = 294, ProductId = 74, Size = "S", StockQuantity = 12 },
new ProductStock { ProductStockId = 295, ProductId = 74, Size = "XS", StockQuantity = 45 },
new ProductStock { ProductStockId = 296, ProductId = 74, Size = "L", StockQuantity = 9 },
new ProductStock { ProductStockId = 297, ProductId = 75, Size = "L", StockQuantity = 37 },
new ProductStock { ProductStockId = 298, ProductId = 75, Size = "S", StockQuantity = 36 },
new ProductStock { ProductStockId = 299, ProductId = 75, Size = "M", StockQuantity = 45 },
new ProductStock { ProductStockId = 300, ProductId = 75, Size = "XL", StockQuantity = 17 },
new ProductStock { ProductStockId = 301, ProductId = 76, Size = "L", StockQuantity = 24 },
new ProductStock { ProductStockId = 302, ProductId = 76, Size = "XS", StockQuantity = 48 },
new ProductStock { ProductStockId = 303, ProductId = 76, Size = "XL", StockQuantity = 8 },
new ProductStock { ProductStockId = 304, ProductId = 76, Size = "S", StockQuantity = 16 },
new ProductStock { ProductStockId = 305, ProductId = 77, Size = "XS", StockQuantity = 50 },
new ProductStock { ProductStockId = 306, ProductId = 77, Size = "L", StockQuantity = 27 },
new ProductStock { ProductStockId = 307, ProductId = 77, Size = "S", StockQuantity = 50 },
new ProductStock { ProductStockId = 308, ProductId = 77, Size = "M", StockQuantity = 50 },
new ProductStock { ProductStockId = 309, ProductId = 78, Size = "L", StockQuantity = 28 },
new ProductStock { ProductStockId = 310, ProductId = 78, Size = "XS", StockQuantity = 10 },
new ProductStock { ProductStockId = 311, ProductId = 78, Size = "S", StockQuantity = 22 },
new ProductStock { ProductStockId = 312, ProductId = 78, Size = "XL", StockQuantity = 49 },
new ProductStock { ProductStockId = 313, ProductId = 79, Size = "XL", StockQuantity = 18 },
new ProductStock { ProductStockId = 314, ProductId = 79, Size = "M", StockQuantity = 13 },
new ProductStock { ProductStockId = 315, ProductId = 79, Size = "XS", StockQuantity = 10 },
new ProductStock { ProductStockId = 316, ProductId = 79, Size = "L", StockQuantity = 16 },
new ProductStock { ProductStockId = 317, ProductId = 80, Size = "S", StockQuantity = 6 },
new ProductStock { ProductStockId = 318, ProductId = 80, Size = "L", StockQuantity = 6 },
new ProductStock { ProductStockId = 319, ProductId = 80, Size = "XL", StockQuantity = 11 },
new ProductStock { ProductStockId = 320, ProductId = 80, Size = "XS", StockQuantity = 15 },
new ProductStock { ProductStockId = 321, ProductId = 81, Size = "S", StockQuantity = 24 },
new ProductStock { ProductStockId = 322, ProductId = 81, Size = "XL", StockQuantity = 48 },
new ProductStock { ProductStockId = 323, ProductId = 81, Size = "L", StockQuantity = 47 },
new ProductStock { ProductStockId = 324, ProductId = 81, Size = "M", StockQuantity = 9 },
new ProductStock { ProductStockId = 325, ProductId = 82, Size = "L", StockQuantity = 48 },
new ProductStock { ProductStockId = 326, ProductId = 82, Size = "M", StockQuantity = 24 },
new ProductStock { ProductStockId = 327, ProductId = 82, Size = "XS", StockQuantity = 27 },
new ProductStock { ProductStockId = 328, ProductId = 82, Size = "S", StockQuantity = 33 },
new ProductStock { ProductStockId = 329, ProductId = 83, Size = "S", StockQuantity = 46 },
new ProductStock { ProductStockId = 330, ProductId = 83, Size = "XL", StockQuantity = 34 },
new ProductStock { ProductStockId = 331, ProductId = 83, Size = "XS", StockQuantity = 8 },
new ProductStock { ProductStockId = 332, ProductId = 83, Size = "M", StockQuantity = 43 },
new ProductStock { ProductStockId = 333, ProductId = 84, Size = "S", StockQuantity = 27 },
new ProductStock { ProductStockId = 334, ProductId = 84, Size = "L", StockQuantity = 49 },
new ProductStock { ProductStockId = 335, ProductId = 84, Size = "XL", StockQuantity = 41 },
new ProductStock { ProductStockId = 336, ProductId = 84, Size = "M", StockQuantity = 14 },
new ProductStock { ProductStockId = 337, ProductId = 85, Size = "XL", StockQuantity = 22 },
new ProductStock { ProductStockId = 338, ProductId = 85, Size = "M", StockQuantity = 27 },
new ProductStock { ProductStockId = 339, ProductId = 85, Size = "L", StockQuantity = 45 },
new ProductStock { ProductStockId = 340, ProductId = 85, Size = "XS", StockQuantity = 13 },
new ProductStock { ProductStockId = 341, ProductId = 86, Size = "L", StockQuantity = 17 },
new ProductStock { ProductStockId = 342, ProductId = 86, Size = "S", StockQuantity = 25 },
new ProductStock { ProductStockId = 343, ProductId = 86, Size = "XL", StockQuantity = 18 },
new ProductStock { ProductStockId = 344, ProductId = 86, Size = "M", StockQuantity = 6 },
new ProductStock { ProductStockId = 345, ProductId = 87, Size = "XS", StockQuantity = 17 },
new ProductStock { ProductStockId = 346, ProductId = 87, Size = "S", StockQuantity = 46 },
new ProductStock { ProductStockId = 347, ProductId = 87, Size = "XL", StockQuantity = 28 },
new ProductStock { ProductStockId = 348, ProductId = 87, Size = "M", StockQuantity = 48 },
new ProductStock { ProductStockId = 349, ProductId = 88, Size = "L", StockQuantity = 37 },
new ProductStock { ProductStockId = 350, ProductId = 88, Size = "M", StockQuantity = 44 },
new ProductStock { ProductStockId = 351, ProductId = 88, Size = "XS", StockQuantity = 5 },
new ProductStock { ProductStockId = 352, ProductId = 88, Size = "S", StockQuantity = 5 },
new ProductStock { ProductStockId = 353, ProductId = 89, Size = "XS", StockQuantity = 23 },
new ProductStock { ProductStockId = 354, ProductId = 89, Size = "L", StockQuantity = 10 },
new ProductStock { ProductStockId = 355, ProductId = 89, Size = "S", StockQuantity = 33 },
new ProductStock { ProductStockId = 356, ProductId = 89, Size = "M", StockQuantity = 47 },
new ProductStock { ProductStockId = 357, ProductId = 90, Size = "M", StockQuantity = 15 },
new ProductStock { ProductStockId = 358, ProductId = 90, Size = "XL", StockQuantity = 37 },
new ProductStock { ProductStockId = 359, ProductId = 90, Size = "XS", StockQuantity = 24 },
new ProductStock { ProductStockId = 360, ProductId = 90, Size = "S", StockQuantity = 28 },
new ProductStock { ProductStockId = 361, ProductId = 91, Size = "XL", StockQuantity = 7 },
new ProductStock { ProductStockId = 362, ProductId = 91, Size = "M", StockQuantity = 13 },
new ProductStock { ProductStockId = 363, ProductId = 91, Size = "L", StockQuantity = 7 },
new ProductStock { ProductStockId = 364, ProductId = 91, Size = "S", StockQuantity = 24 },
new ProductStock { ProductStockId = 365, ProductId = 92, Size = "XL", StockQuantity = 28 },
new ProductStock { ProductStockId = 366, ProductId = 92, Size = "L", StockQuantity = 29 },
new ProductStock { ProductStockId = 367, ProductId = 92, Size = "M", StockQuantity = 37 },
new ProductStock { ProductStockId = 368, ProductId = 92, Size = "XS", StockQuantity = 10 },
new ProductStock { ProductStockId = 369, ProductId = 93, Size = "XL", StockQuantity = 16 },
new ProductStock { ProductStockId = 370, ProductId = 93, Size = "XS", StockQuantity = 23 },
new ProductStock { ProductStockId = 371, ProductId = 93, Size = "L", StockQuantity = 10 },
new ProductStock { ProductStockId = 372, ProductId = 93, Size = "S", StockQuantity = 33 },
new ProductStock { ProductStockId = 373, ProductId = 94, Size = "L", StockQuantity = 10 },
new ProductStock { ProductStockId = 374, ProductId = 94, Size = "XL", StockQuantity = 40 },
new ProductStock { ProductStockId = 375, ProductId = 94, Size = "M", StockQuantity = 12 },
new ProductStock { ProductStockId = 376, ProductId = 94, Size = "S", StockQuantity = 22 },
new ProductStock { ProductStockId = 377, ProductId = 95, Size = "M", StockQuantity = 25 },
new ProductStock { ProductStockId = 378, ProductId = 95, Size = "S", StockQuantity = 45 },
new ProductStock { ProductStockId = 379, ProductId = 95, Size = "L", StockQuantity = 43 },
new ProductStock { ProductStockId = 380, ProductId = 95, Size = "XL", StockQuantity = 48 },
new ProductStock { ProductStockId = 381, ProductId = 96, Size = "XL", StockQuantity = 34 },
new ProductStock { ProductStockId = 382, ProductId = 96, Size = "M", StockQuantity = 23 },
new ProductStock { ProductStockId = 383, ProductId = 96, Size = "S", StockQuantity = 40 },
new ProductStock { ProductStockId = 384, ProductId = 96, Size = "L", StockQuantity = 6 },
new ProductStock { ProductStockId = 385, ProductId = 97, Size = "M", StockQuantity = 46 },
new ProductStock { ProductStockId = 386, ProductId = 97, Size = "S", StockQuantity = 38 },
new ProductStock { ProductStockId = 387, ProductId = 97, Size = "L", StockQuantity = 33 },
new ProductStock { ProductStockId = 388, ProductId = 97, Size = "XL", StockQuantity = 40 },
new ProductStock { ProductStockId = 389, ProductId = 98, Size = "XL", StockQuantity = 19 },
new ProductStock { ProductStockId = 390, ProductId = 98, Size = "XS", StockQuantity = 45 },
new ProductStock { ProductStockId = 391, ProductId = 98, Size = "L", StockQuantity = 7 },
new ProductStock { ProductStockId = 392, ProductId = 98, Size = "M", StockQuantity = 30 },
new ProductStock { ProductStockId = 393, ProductId = 99, Size = "L", StockQuantity = 38 },
new ProductStock { ProductStockId = 394, ProductId = 99, Size = "M", StockQuantity = 10 },
new ProductStock { ProductStockId = 395, ProductId = 99, Size = "XL", StockQuantity = 22 },
new ProductStock { ProductStockId = 396, ProductId = 99, Size = "XS", StockQuantity = 33 },
new ProductStock { ProductStockId = 397, ProductId = 100, Size = "XL", StockQuantity = 14 },
new ProductStock { ProductStockId = 398, ProductId = 100, Size = "L", StockQuantity = 50 },
new ProductStock { ProductStockId = 399, ProductId = 100, Size = "S", StockQuantity = 36 },
new ProductStock { ProductStockId = 400, ProductId = 100, Size = "XS", StockQuantity = 19 }

                );


        }
    }
}
